
tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

brew "awscli"
brew "broot"
brew "curl"
brew "exa"
brew "htop"
brew "jq"
brew "rcm"
brew "ripgrep"
brew "rustup"
brew "zsh-completions"
brew "zsh"

cask "chromium"
cask "discord"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "font-caskaydia-cove-nerd-font"
cask "insomnia"
cask "iterm2"
cask "slack"
cask "visual-studio-code"
cask "whatsapp"

